name: C/C++ CI

on: [push]

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
    - name: start
      shell: bash
      run: ./ov.root install && ov.root start
    - name: install
      shell: ov.bash {0}
      run: |
        ./install.sh --sudo --group r
        ./install.sh --sudo --group rdep
        ./install.sh --sudo --group cuda
        ./install.sh --sudo --group openmpi
        ./install.sh --sudo --group cuda 11.7
    - name: stop
      shell: bash
      run: ov.root stop
    - name: print
      shell: bash
      run: find $(ov.root path) || echo "---- DONE ----"

