name: C/C++ CI

on: [push]

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
    - name: start
      shell: bash
      run: ./ov.root install && ov.root start
    - name: install
      shell: ov.bash {0}
      run: |
        sudo apt-get install joe
    - name: stop
      shell: bash
      run: ov.root stop
    - name: print
      shell: bash
      run: find $(ov.root path)

