name: C/C++ CI

on: [push]

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
    - name: install
      shell: bash
      run: |
        sudo add-apt-repository ppa:deki/firejail || echo "msg: wrong"
        sudo apt-get update || echo "msg: wrong"
        sudo apt-get install firejail firejail-profiles || echo "msg: wrong"
        which joe || echo "msg: wrong"
        mount || echo "msg: wrong"
        firejail --version || echo "msg: wrong"
    - name: run
      shell: bash
      run: |
        tee scr <<EOF
          apt-get install joe || echo "msg: wrong"
          which joe || echo "msg: wrong"
          mount || echo "msg: wrong"
        EOF
        sudo firejail --noprofile --overlay bash scr
