name: C/C++ CI

on: [push]

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
    - name: install
      shell: bash
      run: |
        sudo add-apt-repository ppa:deki/firejail
        sudo apt-get update
        sudo apt-get install firejail firejail-profiles
        which joe
    - name: run
      shell: sudo firejail --noprofile --overlay-tmpfs
      run: |
        apt-get install joe
        which joe
