name: C/C++ CI

on: [push]

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
    - uses: llaniewski/checkout@v1
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
  build2:
    runs-on: self-hosted
    steps:
    - uses: llaniewski/checkout@v1
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
