name: C/C++ CI

on: [push]

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
    - name: install
      id: install
      shell: bash
      run: |
        make
        echo $USER
        echo "user=$USER" >>$GITHUB_OUTPUT
        mkdir test
    - name: run
      shell: sudo ./ovroot test /usr/bin/bash --noprofile --norc -e -o pipefail {0}
      run: |
        chmod 755 / 
        su ${{ steps.install.outputs.user }}
        sudo apt-get update
        sudo apt-get install joe
    - name: print
      shell: bash
      run: find test/

