name: C/C++ CI

on: [push]

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
    - name: install
      shell: bash
      run: |
        make
        mkdir test
    - name: run
      shell: sudo ./ovroot test bash {0}
      run: apt-get install joe
    - name: print
      shell: bash
      run: find test/

